version: '3.3'

services:
  docker-influxdb-grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    container_name: docker-influxdb-grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./setup.sh:/setup.sh
      - ./influxdb/data/data:/var/lib/influxdb/data
      - ./influxdb/data/log:/var/lib/influxdb/log
      - ./influxdb/log:/var/log/influxdb
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-root}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-root}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    restart: unless-stopped
    ports:
      - 3003:3003
      - 3004:8083
      - 8086:8086
